### ISSUE TITLE
Meteor panic when run tests

### ISSUE THREAD

**Issue by newsiberian** [mikowals/batch-insert#13]
Hi, I faced with the following error while running tests, it this mean something to you?

```
W20151225-19:50:19.558(6)? (STDERR)           
W20151225-19:50:19.559(6)? (STDERR) /home/sohaam/.meteor/packages/meteor-tool/.1.1.10.gjfrq3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151225-19:50:19.560(6)? (STDERR)                                             throw(ex);
W20151225-19:50:19.560(6)? (STDERR)                                                   ^
W20151225-19:50:19.653(6)? (STDERR) Error: A method named '/Products/insert' is already defined
W20151225-19:50:19.653(6)? (STDERR)     at meteor://💻app/livedata_server.js:1542:15
W20151225-19:50:19.653(6)? (STDERR)     at Function._.each._.forEach (meteor://💻app/packages/underscore/underscore.js:113:1)
W20151225-19:50:19.653(6)? (STDERR)     at [object Object]._.extend.methods (meteor://💻app/livedata_server.js:1538:7)
W20151225-19:50:19.653(6)? (STDERR)     at [object Object].Mongo.Collection._defineMutationMethods (meteor://💻app/packages/mongo/collection.js:927:1)
W20151225-19:50:19.653(6)? (STDERR)     at [object Object].Mongo.Collection (meteor://💻app/packages/mongo/collection.js:218:1)
W20151225-19:50:19.653(6)? (STDERR)     at [object Object].ns.Collection (meteor://💻app/packages/matb33_collection-hooks/collection-hooks.js:244:1)
W20151225-19:50:19.653(6)? (STDERR)     at new Mongo.Collection (meteor://💻app/packages/mikowals_batch-insert/batch-insert-common.js:101:1)
W20151225-19:50:19.654(6)? (STDERR)     at allTrue.insert (meteor://💻app/packages/local-test_aldeed_collection2/tests/collections.js:91:1)
W20151225-19:50:19.654(6)? (STDERR)     at /tmp/meteor-test-runlg927q/.meteor/local/build/programs/server/packages/local-test_aldeed_collection2.js:415:4
W20151225-19:50:19.654(6)? (STDERR)     at /tmp/meteor-test-runlg927q/.meteor/local/build/programs/server/packages/local-test_aldeed_collection2.js:1579:3
W20151225-19:50:19.654(6)? (STDERR)     at /tmp/meteor-test-runlg927q/.meteor/local/build/programs/server/boot.js:242:10
W20151225-19:50:19.654(6)? (STDERR)     at Array.forEach (native)
W20151225-19:50:19.654(6)? (STDERR)     at Function._.each._.forEach (/home/sohaam/.meteor/packages/meteor-tool/.1.1.10.gjfrq3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151225-19:50:19.654(6)? (STDERR)     at /tmp/meteor-test-runlg927q/.meteor/local/build/programs/server/boot.js:137:5
```

**Comment by mikowals** [comment]
it looks like you are creating two collections named `Products` and the second creation fails because of a name conflict while it is creating the insert method.  In testing creating [random collection names](https://github.com/mikowals/batch-insert/blob/master/batch-insert-tests.js#L52) for each test can help avoid any name collisions.

I don't think this is related to this package since it is the `insert` method.

**Comment by newsiberian** [comment]
Thanks, you were right about two names.
