### ISSUE TITLE
Batch insert failing on the server for huge amount of data

### ISSUE THREAD

**Issue by franzip** [mikowals/batch-insert#16]
I'm using `mikowals:batch-insert@1.1.9` on a Meteor/OrionJS app.
On the local dev environment the insertion of millions of documents with batch-insert works and that takes only a few seconds.
On our staging server (running on EC2 nginx), batch-insert fails when dealing with more than  approximately ~100k documents to insert.

Here's the code that get executed on the server:

```
var stuffToInsert = [];
_.each(thing, function(element){
  stuffToInsert.push({
    // ...
  });
});

// tag-manager.js:63:9
Collection.batchInsert(stuffToInsert);

```

And here's the error stack provided by PM2:

```
dashboard-19 (out):     at packages/meteor/helpers.js:119:1
dashboard-19 (out):     at _batchInsert (packages/mikowals:batch-insert/batch-insert-server.js:112:1)
dashboard-19 (out):     at [object Object].Mongo.Collection.batchInsert (packages/mikowals:batch-insert/batch-insert-common.js:89:1)
dashboard-19 (out):     at [object Object].Meteor.methods.generateTags (app/server/tag-manager.js:63:9)
dashboard-19 (out):     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
dashboard-19 (out):     at packages/ddp/livedata_server.js:648:1
dashboard-19 (out):     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
dashboard-19 (out):     at packages/ddp/livedata_server.js:647:1
dashboard-19 (out):     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
dashboard-19 (out):     - - - - -
dashboard-19 (out):     at [object Object].InsertCommand.toBinary (/var/www/viveat/dashboard/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/commands/insert_command.js:86:11)
dashboard-19 (out):     at [object Object].Connection.write (/var/www/viveat/dashboard/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:252:42)
dashboard-19 (out):     at __executeInsertCommand (/var/www/viveat/dashboard/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1953:14)
dashboard-19 (out):     at Db._executeInsertCommand (/var/www/viveat/dashboard/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:2026:5)
dashboard-19 (out):     at insertAll (/var/www/viveat/dashboard/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/collection/core.js:249:13)
dashboard-19 (out):     at Collection.insert (/var/www/viveat/dashboard/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/collection/core.js:36:3)
dashboard-19 (out):     at packages/meteor/helpers.js:118:1
dashboard-19 (out):     at _batchInsert (packages/mikowals:batch-insert/batch-insert-server.js:112:1)
dashboard-19 (out):     at [object Object].Mongo.Collection.batchInsert (packages/mikowals:batch-insert/batch-insert-common.js:89:1)
dashboard-19 (out):     at [object Object].Meteor.methods.generateTags (app/server/tag-manager.js:63:9)
```

**Comment by mikowals** [comment]
There isn't enough information here for me to add anything.  Usually if the inserts are throwing an error there is an error message along with the stack trace which give a clue about exactly what is going wrong.

If the insert is large and it only happens on your server maybe some debugging steps would be:
1. do the insert in meteor shell with `Mongo.Collection.rawCollection().insert(stuffToInsert)`
2. do the insert in mongo shell

I expect one or both of these would error and give you more information about what is happening.  Let me know how you go.
