### ISSUE TITLE
Clash with ground:db

### ISSUE THREAD

**Issue by joaopiopedreira** [mikowals/batch-insert#17]
Hi,

Just tried to install this package in my Meteor project today (meteor@1.2).

It apparently clashes with [ground:db](https://github.com/GroundMeteor/db). Here's the error stack:

```
W20160206-23:11:27.055(0)? (STDERR) 
W20160206-23:11:27.057(0)? (STDERR) /Users/joaopedreira/.meteor/packages/meteor-tool/.1.1.10.1r5n12p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160206-23:11:27.057(0)? (STDERR)                         throw(ex);
W20160206-23:11:27.057(0)? (STDERR)                               ^
W20160206-23:11:27.057(0)? (STDERR) Error: use "new" to construct a Mongo.Collection
W20160206-23:11:27.057(0)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:29:1)
W20160206-23:11:27.057(0)? (STDERR)     at new Ground.Collection (packages/ground_db/groundDB.server.js:81:1)
W20160206-23:11:27.057(0)? (STDERR)     at lib/collections.js:12:1
W20160206-23:11:27.057(0)? (STDERR)     at lib/collections.js:177:1
W20160206-23:11:27.057(0)? (STDERR)     at /Users/joaopedreira/WebstormProjects/RoutesDirectMobile/.meteor/local/build/programs/server/boot.js:242:10
W20160206-23:11:27.057(0)? (STDERR)     at Array.forEach (native)
W20160206-23:11:27.057(0)? (STDERR)     at Function._.each._.forEach (/Users/joaopedreira/.meteor/packages/meteor-tool/.1.1.10.1r5n12p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160206-23:11:27.057(0)? (STDERR)     at /Users/joaopedreira/WebstormProjects/RoutesDirectMobile/.meteor/local/build/programs/server/boot.js:137:5
```

Any ideas? Thanks

**Comment by joaopiopedreira** [comment]
It fails even without ground:db.

```
Error: First argument to new Mongo.Collection must be a string or null
W20160209-12:40:21.793(0)? (STDERR)     at [object Object].Mongo.Collection (packages/mongo/collection.js:39:1)
W20160209-12:40:21.793(0)? (STDERR)     at new Mongo.Collection (packages/mikowals_batch-insert/batch-insert-common.js:101:1)
```

I'm using Meteor 1.2.1. Cheers

**Comment by mikowals** [comment]
This package doesn't create any collections so I don't think these errors relate to this package.   The first one says you called `Mongo.Collection(...)` rather than `new Mongo.Collection(...)`.  The second says your first argument when creating a new collection must be a string or null.  

If that is not the case just share a minimal reproduction of the issue and I will have a look.
