### ISSUE TITLE
Doesn't work with vsivsi meteor-job collection

### ISSUE THREAD

**Issue by milosgacanovic** [mikowals/batch-insert#9]
/Users/mg/.meteor/packages/meteor-tool/.1.1.8.tvnipv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: The global definition of Mongo.Collection has changed since the job-collection package was loaded. Please ensure that any packages that redefine Mongo.Collection are loaded before job-collection.
    at JobCollectionBase (packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:1520:1)
    at new JobCollection (packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:3034:1)
    at JobCollection (packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:3032:1)
    at insocl_crawler.js:59:14
    at /Users/mg/www/insocl_crawler/.meteor/local/build/programs/server/app/insocl_crawler.js:324:4
    at /Users/mg/www/insocl_crawler/.meteor/local/build/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/mg/.meteor/packages/meteor-tool/.1.1.8.tvnipv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/mg/www/insocl_crawler/.meteor/local/build/programs/server/boot.js:137:5

**Comment by mikowals** [comment]
I am not familiar with that package but have you followed the instructions in the error message to "ensure that any packages that redefine Mongo.Collection are loaded before job-collection"?

mikowals:batch-insert does of course redefine Mongo.Collection so that each new collection created has the necessary methods.

**Comment by milosgacanovic** [comment]
Yes, just changing order in packages file fixed it. Thanks :)

**Comment by mikowals** [comment]
Great.  Thanks for reporting back.
